import type {Metadata} from 'next';
import './globals.css';
import {ReactNode} from 'react';
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: 'Portfolio - Mathieu Stamm',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {

    return (
        <html lang="fr" className="dark:bg-black bg-white">
        <body className="flex flex-col min-h-screen bg-code">
        <header>
            <Navbar/>
        </header>
        <main className="container mx-auto flex-grow p-4">
            {children}
        </main>
        <footer className="bg-gray-800 text-white">
            <Footer/>
        </footer>
        </body>
        </html>
    );
}
